# exclude: '^$'
fail_fast: false
repos:
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.7
    hooks:
    -   id: flake8
        stages: [commit, push]
-   repo: https://github.com/psf/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.6
      stages: [commit, push]
-   repo: local
    hooks:
    -   id: pytest
        name: pytest
        entry: pytest -v
        language: python
        always_run: true
        pass_filenames: false
        types: [python]
        stages: [push]
